### ISSUE TITLE
Bug: Authentication exception.  Rpc responds indicating valid metadata headers required.

### ISSUE THREAD

**Issue by kyleballard** [pozil/pub-sub-api-node-client#14]
## What happens

After client has connected to pubsub API successfully, and an event occurs on the topic (i.e. /data/AccountChangeEvent), then the client aborts with the output inside Error Output below.

## How to Reproduce

Follow instructions as provided in README.md, use any authentication method.  In my case, I am using username-password.

## Other details

I am able to independently confirm that gRPC connection metaCallback object is given the correct accessToken, instanceUrl and tenantId as returned by jsForce library.    I have obfuscated by login as "my@user.com" and my machine username as "myuser" in error output below.

## Error Output

```sh
Connected to Salesforce org https://myinstance.develop.my.salesforce.com as my@user.com
Connected to Pub/Sub API endpoint api.pubsub.salesforce.com:7443
Error: Failed to subscribe to events for topic /data/AccountChangeEvent
    at #subscribe (file:///Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/salesforce-pubsub-api-client/dist/client.js:568:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (file:///Users/myuser/Projects/salesforce-projects/pubsub-demo/sample.js:9:26) {
  [cause]: Error: Failed to load schema for topic /data/AccountChangeEvent
      at #getEventSchema (file:///Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/salesforce-pubsub-api-client/dist/client.js:639:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async #subscribe (file:///Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/salesforce-pubsub-api-client/dist/client.js:527:22)
      at async run (file:///Users/myuser/Projects/salesforce-projects/pubsub-demo/sample.js:9:26) {
    [cause]: Error: 16 UNAUTHENTICATED: An authentication exception occurred. Provide valid authentication via metadata headers. rpcId: a47a28a4-05a1-43ff-9815-f2ca4fb3d336
        at callErrorFromStatus (/Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
        at Object.onReceiveStatus (/Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
        at Object.onReceiveStatus (/Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
        at Object.onReceiveStatus (/Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
        at /Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
    for call at
        at ServiceClientImpl.makeUnaryRequest (/Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
        at ServiceClientImpl.<anonymous> (/Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
        at file:///Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/salesforce-pubsub-api-client/dist/client.js:654:20
        at new Promise (<anonymous>)
        at #fetchEventSchemaWithClient (file:///Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/salesforce-pubsub-api-client/dist/client.js:653:12)
        at #getEventSchema (file:///Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/salesforce-pubsub-api-client/dist/client.js:636:56)
        at #subscribe (file:///Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/salesforce-pubsub-api-client/dist/client.js:527:48)
        at PubSubApiClient.subscribe (file:///Users/myuser/Projects/salesforce-projects/pubsub-demo/node_modules/salesforce-pubsub-api-client/dist/client.js:511:27)
        at run (file:///Users/myuser/Projects/salesforce-projects/pubsub-demo/sample.js:9:39)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      code: 16,
      details: 'An authentication exception occurred. Provide valid authentication via metadata headers. rpcId: a47a28a4-05a1-43ff-9815-f2ca4fb3d336',
      metadata: [Metadata]
    }
  }
}
```

**Comment by pozil** [comment]
Hi @kyleballard. Unfortunately, I can't reproduce on my end.
Could it be a temporary issue with the Pub Sub API?
Is there anything else that could cause the issue on this org in particular (type of org, API version...)?

As a side note, I just released a new version with updated dependencies but it shouldn't doesn't affect your issue.

**Comment by nktnet1** [comment]
Potentially related to https://github.com/pozil/pub-sub-api-node-client/issues/67#issuecomment-3766007431
