### ISSUE TITLE
subscribeFromReplayId does not work with -1 or -2

### ISSUE THREAD

**Issue by eltoroit** [pozil/pub-sub-api-node-client#20]
Based on this [trailhead page](https://trailhead.salesforce.com/content/learn/modules/api_basics/api_basics_streaming), we should be able to use -1 or -2 for the ReplayId to retrieve older events we could have missed.

But I get the following error when calling this function `client.subscribeFromReplayId(channel, 100, -1);`:

```
Connected to Salesforce org https://platform-dream-3455-dev-ed.scratch.my.salesforce.com as test-wm37brzzizwl@example.com
Connected to Pub/Sub API endpoint api.pubsub.salesforce.com:7443
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0n and < 2n ** 64n. Received -1n
    at new NodeError (node:internal/errors:405:5)
    at checkInt (node:internal/buffer:74:11)
    at writeBigU_Int64BE (node:internal/buffer:607:3)
    at Buffer.writeBigUInt64BE (node:internal/buffer:629:10)
    at encodeReplayId (file:///Users/aperez/Git%20Projects/current/HOWs/RealTimeSalesforce/GitHub/gRPC/PubSub/node_modules/salesforce-pubsub-api-client/dist/client.js:209:7)
    at PubSubApiClient.subscribeFromReplayId (file:///Users/aperez/Git%20Projects/current/HOWs/RealTimeSalesforce/GitHub/gRPC/PubSub/node_modules/salesforce-pubsub-api-client/dist/client.js:543:17)
    at file:///Users/aperez/Git%20Projects/current/HOWs/RealTimeSalesforce/GitHub/gRPC/PubSub/pubSubClient.js:14:25
    at new Promise (<anonymous>)
    at subscribe (file:///Users/aperez/Git%20Projects/current/HOWs/RealTimeSalesforce/GitHub/gRPC/PubSub/pubSubClient.js:12:10)
    at run (file:///Users/aperez/Git%20Projects/current/HOWs/RealTimeSalesforce/GitHub/gRPC/PubSub/pubSubClient.js:42:10) {
  code: 'ERR_OUT_OF_RANGE'
}

Node.js v18.17.0
```

**Comment by pozil** [comment]
The -1 and -2 ReplayID trick was true for the CometD client. Pub/Sub API has the same replay capabilities but doesn't work like this. I exposed some dedicated methods on the client for these use cases. See the readme.
