### ISSUE TITLE
Unable to parse Opportunity events

### ISSUE THREAD

**Issue by kunalrgarg** [pozil/pub-sub-api-node-client#25]
We are unable to successfully parse events from Account/Opportunity and other objects. This issue is occuring in a sandbox environment. Other developer and prod environments work as expected for said objects

```
/Users/.../node_modules/avro-js/lib/schemas.js:464
    throw new Error('potential precision loss');
          ^

Error: potential precision loss
    at LongType._read (/Users/.../node_modules/avro-js/lib/schemas.js:464:11)
    at RecordType.readChangeEventHeader [as _read] (eval at RecordType._createReader (/Users/.../node_modules/avro-js/lib/schemas.js:1563:10), <anonymous>:4:133)
    at RecordType.readOpportunityChangeEvent [as _read] (eval at RecordType._createReader (/Users/.../node_modules/avro-js/lib/schemas.js:1563:10), <anonymous>:4:40)
    at readValue (/Users/.../node_modules/avro-js/lib/schemas.js:2015:17)
    at Type.fromBuffer (/Users/.../node_modules/avro-js/lib/schemas.js:247:13)
    at parseEvent (/Users/.../node_modules/salesforce-pubsub-api-client/dist/client.cjs:143:31)
    at /Users/.../node_modules/salesforce-pubsub-api-client/dist/client.cjs:622:33
    at Array.forEach (<anonymous>)
    at ClientDuplexStreamImpl.<anonymous> (/Users/.../node_modules/salesforce-pubsub-api-client/dist/client.cjs:621:23)
    at ClientDuplexStreamImpl.emit (node:events:512:28)
```

this is the event that is referenced in client.cjs:143:31 (event has been sanitized)
```
{
  event: {
    id: '00xx00x0-000x-0xx0-0xx0-0x0xx00000x0',
    schemaId: 'XX0XxXX0XXx0xXxX0xxxXX',
    payload: <Buffer <sanitized> ... 286 more bytes>
  },
  replayId: <Buffer ... <sanitized> ... >
}
```

**Comment by pozil** [comment]
hi @kunalrgarg, are you using the latest version of the library?
We had a similar issue (#21) with Long number precision in Avro-JS but it was fixed.

**Comment by kunalrgarg** [comment]
Version 3.4.0 worked, thank you!
