### ISSUE TITLE
Uncaught Error: Channel has been shut down

### ISSUE THREAD

**Issue by rjruigrok** [pozil/pub-sub-api-node-client#28]
Hi @pozil, thanks for all your work on this client! 

Today I saw the following issue coming by, when reconnecting to a replayid from a few hours before. In the meantime the schema had slightly changed, since then the client was not able anymore to avro decode the earlier events. These resulted all in clear 'EventParseError' errors; which is for now fine. 

But the app still crashed on an uncatched error. I have put the stacktrace below:

```
/dist/node_modules/salesforce-pubsub-api-client/node_modules/@grpc/grpc-js/src/internal-channel.ts:835
      throw new Error('Channel has been shut down');
      ^


Error: Channel has been shut down
    at InternalChannel.createCall (/dist/node_modules/salesforce-pubsub-api-client/node_modules/@grpc/grpc-js/src/internal-channel.ts:835:13)
    at ChannelImplementation.createCall (/dist/node_modules/salesforce-pubsub-api-client/node_modules/@grpc/grpc-js/src/channel.ts:166:33)
    at getCall (/dist/node_modules/salesforce-pubsub-api-client/node_modules/@grpc/grpc-js/src/client-interceptors.ts:349:24)
    at getBottomInterceptingCall (/dist/node_modules/salesforce-pubsub-api-client/node_modules/@grpc/grpc-js/src/client-interceptors.ts:480:16)
    at <anonymous> (/dist/node_modules/salesforce-pubsub-api-client/node_modules/@grpc/grpc-js/src/client-interceptors.ts:574:7)
    at getInterceptingCall (/dist/node_modules/salesforce-pubsub-api-client/node_modules/@grpc/grpc-js/src/client-interceptors.ts:576:10)
    at ServiceClientImpl.makeUnaryRequest (/dist/node_modules/salesforce-pubsub-api-client/node_modules/@grpc/grpc-js/src/client.ts:312:64)
    at ServiceClientImpl.<anonymous> (/dist/node_modules/salesforce-pubsub-api-client/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at Object.callback (/dist/node_modules/salesforce-pubsub-api-client/dist/client.cjs:943:24)
    at Object.onReceiveStatus (/dist/node_modules/salesforce-pubsub-api-client/node_modules/@grpc/grpc-js/src/client.ts:356:28)

Node.js v20.11.1

```

Do you know a way this can also be catched into an error event?

**Comment by pozil** [comment]
Hi @rjruigrok looking at the stack trace that you provided this seems related to the error with custom channel (client fails to retrieve the schema because the custom channel topic doesn't expose a schema ID).
The latest version should address this.

**Comment by pozil** [comment]
Hi @rjruigrok did the issue persist with the latest client?
