### ISSUE TITLE
Code in README.md does not work. Error: TypeError: Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by eltoroit** [pozil/pub-sub-api-node-client#33]
I tried the code in the README.md file, but it's failing when the data is received. This is the error:

```
file:///Users/aperez/Git%20Projects/current/ARC101/2024/grpc/node_modules/salesforce-pubsub-api-client/dist/client.js:825
              const parseError = new EventParseError(
                                 ^

EventParseError: Failed to parse event with replay ID 113730
    at file:///Users/aperez/Git%20Projects/current/ARC101/2024/grpc/node_modules/salesforce-pubsub-api-client/dist/client.js:825:34
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on PubSubEventEmitter instance at:
    at PubSubEventEmitter.emit (file:///Users/aperez/Git%20Projects/current/ARC101/2024/grpc/node_modules/salesforce-pubsub-api-client/dist/client.js:147:18)
    at file:///Users/aperez/Git%20Projects/current/ARC101/2024/grpc/node_modules/salesforce-pubsub-api-client/dist/client.js:832:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: TypeError: Do not know how to serialize a BigInt
      at JSON.stringify (<anonymous>)
      at PubSubEventEmitter.<anonymous> (file:///Users/aperez/Git%20Projects/current/ARC101/2024/grpc/greeter_client.js:21:21)
      at PubSubEventEmitter.emit (node:events:518:28)
      at PubSubEventEmitter.emit (file:///Users/aperez/Git%20Projects/current/ARC101/2024/grpc/node_modules/salesforce-pubsub-api-client/dist/client.js:147:18)
      at file:///Users/aperez/Git%20Projects/current/ARC101/2024/grpc/node_modules/salesforce-pubsub-api-client/dist/client.js:817:28
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5),
  replayId: 113730,
  event: {
    event: {
      id: 'd9e6521b-8e49-427c-9f8b-4cc5dd3c6070',
      schemaId: 'fvNi01PVr47z-BJWOS24fw',
      payload: Buffer(309) [Uint8Array] [
         14,  65,  99,  99, 111, 117, 110, 116,   2,  36,  48,  48,
         49,  79,  50,  48,  48,  48,  48,  48,  68,  87, 115,  86,
        100,  73,  65,  76,   0,   0,  86,  99, 111, 109,  47, 115,
         97, 108, 101, 115, 102, 111, 114,  99, 101,  47,  97, 112,
        105,  47, 114, 101, 115, 116,  47,  54,  49,  46,  48,  59,
         99, 108, 105, 101, 110, 116,  61, 112, 111, 115, 116, 109,
         97, 110,  72,  48,  48,  48,  48,  54,  55, 102,  99,  45,
         57,  51,  52,  48,  45,  53,  98,  99,  51,  45, 102, 100,
         53,  49,  45,  51,
        ... 209 more items
      ]
    },
    replayId: Buffer(10) [Uint8Array] [
      0,   0,  0, 0, 0,
      1, 188, 66, 0, 0
    ]
  },
  latestReplayId: 113730
}

Node.js v20.12.2
```

I noticed that changing this line

`console.log(JSON.stringify(event, null, 2));`

To this line 

`console.log(event);`

Seems to work fine, and there is no error!

**Comment by pozil** [comment]
Hi @eltoroit, this is in fact not a bug from the client but an issue with BigInt JSON representation in standard JS.

You can certainly use `console.log(event)` if you don't care about formatting and indentation. However, if you want a nice output, you need to use `JSON.stringify` with some extra parameters like so:

```js
// Safely log event as a JSON string
console.log(
    JSON.stringify(
        event,
        (key, value) =>
            /* Convert BigInt values into strings and keep other types unchanged */
            typeof value === 'bigint' ? value.toString() : value,
        2
    )
);
```

I've updated the doc example and added a [note explaining what's going on](https://github.com/pozil/pub-sub-api-node-client?tab=readme-ov-file#typeerror-do-not-know-how-to-serialize-a-bigint) (pretty crazy IMO).
