### ISSUE TITLE
Error at requesting additional events on version 5.0.0

### ISSUE THREAD

**Issue by elkinming** [pozil/pub-sub-api-node-client#47]
Hello. Recently I have been working with this library for syncing salesforce data on my on database.

I have to keep listening to the salesforce events all the time so I call the "subscribe" function without the request's number param and I works perfect for the first 100 events. 

After that, the library have to request another additional 100 events, and that is the time when I got an error.

I am getting the error "subscription.write is not a function at PubSubApiClient.requestAdditionalEvents (salesforce-pubsub-api-client\dist\client.cjs:892:18) at ClientDuplexStreamImpl. (salesforce-pubsub-api-client\dist\client.cjs:819:22) at process.processTicksAndRejections".

**Comment by pozil** [comment]
Hi @elkinming, thanks for reporting the issue and for your patience. I just fixed the issue in v5.0.1.
